local ShiftLockIcons: { [string]: string } = {
	i1 = "rbxassetid://68308747", 		-- really small white dot with black outline
	i2 = "rbxassetid://11783958279", 	-- small white dot
	i3 = "rbxassetid://9947313248", 	-- really small white dot
	i4 = "rbxassetid://13011886471", 	-- big white crosshairs
	i5 = "rbxassetid://13848600603", 	-- really small white diamond
	i6 = "rbxassetid://16832867429", 	-- really small white square
}

return ShiftLockIcons
